import { CompanyContainer } from "../../styles/companyStyles";

import Head from "next/head";
import FormCardCompany from "../../components/FormCardCompany";
import Header from "../../components/Header";

export default function NewCompanyPage () {

    return (
        <CompanyContainer>
            <Head>
                    <title>Controle de Ponto Eletrônico Online | PontoGO</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="preconnect" href="https://fonts.googleapis.com" />
                    <link rel="preconnect" href="https://fonts.gstatic.com" />
                    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
            <main>
                <FormCardCompany />
            </main>
        </CompanyContainer>
    )
}